# Generated by Django 5.1.3 on 2024-11-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_appointment_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="doctors", new_name="doctor",
        ),
    ]
